# Site settings
title: A Blog By Developers
email: mailamnguyentran@gmail.com
description: > # MaiLam
baseurl: "http://tungns.top" # the subpath of your site, e.g. /blog/
url: "http://tungns.top" # the base hostname & protocol for your site
twitter_username: mailamnguyentran@gmail.com
github_username:  MaiLam

# Build settings
markdown: kramdown

paginate: 4

author: MaiLam

gems: [jekyll-paginate]
