# Site settings
title: A Blog By Developers
email: mailamnguyentran@gmail.com
description: > # Tungns
baseurl: "https://mydaughter.github.io" # the subpath of your site, e.g. /blog/
url: "https://mydaughter.github.io" # the base hostname & protocol for your site
twitter_username: mailamnguyentran@gmail.com
github_username:  Tungns

# Build settings
markdown: kramdown

paginate: 4

author: Tungns

gems: [jekyll-paginate]
