# Site settings
title: My Daughter
email: mailamnguyentran@gmail.com
description: > # My daughter
baseurl: "https://mydaughter.github.io" # the subpath of your site, e.g. /blog/
url: "https://mydaughter.github.io" # the base hostname & protocol for your site
twitter_username: mailamnguyentran@gmail.com
github_username:  mydaughter

# Build settings
markdown: kramdown

paginate: 4

author: Mai Lam

gems: [jekyll-paginate]
